version: '3'
services:
  v2ray:
    image: teddysun/xray
    container_name: xray-core
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - V2RAY_VMESS_AEAD_FORCED=false
    volumes:
      - ./config.json:/etc/xray/config.json
