version: '3'
services:
  v2ray:
    image: v2fly/v2fly-core:latest
    container_name: v2fly-core
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - V2RAY_VMESS_AEAD_FORCED=false
    volumes:
      - ./config.json:/etc/v2ray/config.json